var wast = {};

(function(exports) {
  exports.ConstI32 = function(args) {
    return {
      type: "const_i32",
      value: args.value
    };
  };

  exports.ConstF32 = function(args) {
    return {
      type: "const_f32",
      value: args.value
    };
  };

  // Should only be generated by the parser.
  exports.GetName = function(args) {
    return {
      type: "getname",
      name: args.name
    };
  };

  exports.GetFunction = function(args) {
    return {
      type: "getfunction",
      index: args.index
    };
  };

  exports.GetExtern = function(args) {
    return {
      type: "getextern",
      index: args.index
    };
  };

  exports.GetLocal = function(args) {
    return {
      type: "getlocal",
      index: args.index
    };
  };

  exports.BinaryOp = function(args) {
    return {
      type: "binop",
      left: args.left,
      op: args.op, right:
      args.right
    };
  };

  // Should only be generated by the parser.
  exports.Call = function(args) {
    return {
      type: "call",
      expr: args.expr,
      args: args.args
    };
  };

  exports.CallDirect = function(args) {
    return {
      type: "calldirect",
      func: args.func,
      args: args.args
    };
  };

  exports.CallExternal = function(args) {
    return {
      type: "callexternal",
      func: args.func,
      args: args.args
    };
  };

  exports.Return = function(args) {
    return {
      type: "return",
      expr: args.expr
    };
  };

  exports.If = function(args) {
    return {
      type: "if",
      cond: args.cond,
      t: args.t,
      f: args.f
    };
  };

  exports.Param = function(args) {
    return {
      type: "param",
      name: args.name,
      ptype: args.ptype
    };
  };

  exports.Local = function(args) {
    return {
      type: "local",
      name: args.name,
      ltype: args.ltype,
      index: args.index,
    };
  };

  exports.Function = function(args) {
    return {
      type: "function",
      exportFunc: args.exportFunc,
      name: args.name,
      params: args.params,
      returnType: args.returnType,
      locals: [],
      body: args.body
    };
  };

  exports.Extern = function(args) {
    return {
      type: "extern",
      name: args.name,
      args: args.args,
      returnType: args.returnType
    };
  };

  exports.Module = function(args) {
    return {
      type: "module",
      externs: args.externs,
      funcs: args.funcs,
    };
  };

})(wast);
